/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 50b12a8ca58446f9e388752a34907b8c)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "https://breakaway4here-arch.github.io";
	PRECLOSE_ENABLED: "true";
	PRE_CLOSE_SNAPSHOT: DurableObjectNamespace<import("./index").PrecloseSnapshot>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "PrecloseSnapshot";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "PRECLOSE_ENABLED">> {}
}
